const PRODUCTS_DATA = [
  {
    id: 1,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 2,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 3,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 4,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 5,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 6,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 5,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 6,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 5,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 6,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 5,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 6,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 5,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
  {
    id: 6,
    proName: "Slick formal sneaker shoe",
    realprice: "₹ 4999.00",
    offerPrice: "₹ 2999.00",
    tag: "new",
    link: "/shoe-details",
    proImg: "shoe-1.svg",
  },
];

export default PRODUCTS_DATA;
